[package]
name = "projektwoche-setup"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
confy = "1.0.0"
clap = { version = "4.5.42", features = ["derive"] }
dirs = "6.0.0"
os_info = "3.12.0"