[package]
name = "ratatui-test-json"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"